"""
web_search.py — Web search engine dorking module.

Searches Google, DuckDuckGo, and Yandex using dork queries generated by
:mod:`ai_finder.discovery` to discover URLs of AI agent configuration files.
The returned URLs are candidates that can then be verified and downloaded by
the rest of the pipeline.

Typical usage
-------------
    import asyncio
    from ai_finder.web_search import WebSearcher

    async def main():
        async with WebSearcher() as searcher:
            urls = await searcher.search_with_dorks(
                engines=("duckduckgo",),
                max_dorks=5,
            )
            print(f"Found {len(urls)} candidate URL(s)")

    asyncio.run(main())
"""

from __future__ import annotations

import asyncio
import re
import sys
import webbrowser
from typing import Optional
from urllib.parse import parse_qs, urlparse

import aiohttp
from bs4 import BeautifulSoup

from ai_finder.discovery import GoogleDorkGenerator, WebDorkGenerator
from ai_finder.extractor import DEFAULT_TIMEOUT
from ai_finder.logger import get_logger, build_trace_config
from ai_finder.rate_limiter import RateLimiter

log = get_logger(__name__)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

#: Domains that should never appear in search results (search-engine own
#: pages, ad-redirect hosts, etc.).
_EXCLUDED_DOMAINS: frozenset[str] = frozenset(
    {
        "google.com",
        "google.co.uk",
        "google.co.in",
        "accounts.google.com",
        "support.google.com",
        "maps.google.com",
        "bing.com",
        "duckduckgo.com",
        "yandex.com",
        "yandex.ru",
        "youtube.com",
        "wikipedia.org",
        "w3.org",
    }
)

#: Browser-like User-Agent used for search-engine requests.
_SEARCH_USER_AGENT = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
    "AppleWebKit/537.36 (KHTML, like Gecko) "
    "Chrome/120.0.0.0 Safari/537.36"
)

#: Default HTTP headers sent with every search-engine request.
_SEARCH_HEADERS: dict[str, str] = {
    "User-Agent": _SEARCH_USER_AGENT,
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
    "Accept-Language": "en-US,en;q=0.5",
}


# ---------------------------------------------------------------------------
# Dork-list builder
# ---------------------------------------------------------------------------

#: Valid values for the ``dork_sources`` parameter of
#: :meth:`WebSearcher.search_with_dorks`.
DORK_SOURCES = frozenset({"github", "web", "all"})


def _build_dorks(
    dork_sources: str,
) -> list:
    """Return the combined dork list for *dork_sources*.

    Parameters
    ----------
    dork_sources:
        One of ``"github"``, ``"web"``, or ``"all"``.

    Returns
    -------
    list[:class:`~ai_finder.discovery.SearchQuery`]
        Deduplicated list of dork queries for the requested sources.

    Raises
    ------
    ValueError
        If *dork_sources* is not a recognised value.
    """
    if dork_sources not in DORK_SOURCES:
        raise ValueError(
            f"Invalid dork_sources={dork_sources!r}. "
            f"Must be one of: {sorted(DORK_SOURCES)}"
        )

    seen: set[str] = set()
    result = []

    def _add(queries):
        for q in queries:
            if q.query not in seen:
                seen.add(q.query)
                result.append(q)

    if dork_sources in ("github", "all"):
        _add(GoogleDorkGenerator().all_dorks())
    if dork_sources in ("web", "all"):
        _add(WebDorkGenerator().all_dorks())

    return result


# ---------------------------------------------------------------------------
# WebSearcher
# ---------------------------------------------------------------------------


class WebSearcher:
    """Search Google, Bing, DuckDuckGo, and Yandex using dork queries.

    Results are parsed from the HTML search-result pages and returned as a
    list of external URLs.  The caller is responsible for verifying
    reachability and downloading content.

    Parameters
    ----------
    session:
        Optional pre-existing :class:`aiohttp.ClientSession`.  When omitted
        the searcher manages its own session lifecycle.
    timeout:
        ``aiohttp.ClientTimeout`` applied to every HTTP request.
    headers:
        HTTP headers sent with every search-engine request.  Defaults to
        browser-like headers to reduce bot-detection friction.
    request_delay:
        Seconds to sleep between consecutive dork queries to avoid
        triggering rate-limit responses from search engines.
    """

    def __init__(
        self,
        session: Optional[aiohttp.ClientSession] = None,
        timeout: aiohttp.ClientTimeout = DEFAULT_TIMEOUT,
        headers: Optional[dict[str, str]] = None,
        request_delay: float = 2.0,
        captcha_pause: bool = True,
        rate_limiter: Optional[RateLimiter] = None,
    ) -> None:
        self._session = session
        self._owns_session = session is None
        self._timeout = timeout
        self._headers = headers if headers is not None else _SEARCH_HEADERS
        self._request_delay = request_delay
        self._captcha_pause = captcha_pause
        self._rate_limiter = rate_limiter if rate_limiter is not None else RateLimiter()
        # Engines that have been blocked (CAPTCHA / persistent 429) during
        # this session.  Once an engine is added here every subsequent query
        # is skipped immediately without making an HTTP request.
        self._blocked_engines: set[str] = set()

    # ------------------------------------------------------------------
    # Session lifecycle
    # ------------------------------------------------------------------

    async def __aenter__(self) -> "WebSearcher":
        if self._owns_session:
            self._session = aiohttp.ClientSession(
                timeout=self._timeout,
                headers=self._headers,
                trace_configs=[build_trace_config()],
            )
        return self

    async def __aexit__(self, *_: object) -> None:
        if self._owns_session and self._session:
            await self._session.close()

    # ------------------------------------------------------------------
    # Public search API
    # ------------------------------------------------------------------

    async def search_duckduckgo(
        self, query: str, *, max_results: int = 10
    ) -> list[str]:
        """Search DuckDuckGo (HTML endpoint) and return result URLs.

        Uses the ``html.duckduckgo.com`` endpoint which does not require
        JavaScript and is friendlier to programmatic access than the
        JavaScript-rendered default interface.

        Parameters
        ----------
        query:
            The search query / dork string.
        max_results:
            Maximum number of URLs to return.

        Returns
        -------
        list[str]
            External HTTP/HTTPS URLs extracted from the result page.
        """
        if "duckduckgo" in self._blocked_engines:
            return []
        log.info("duckduckgo  query=%r", query)
        await self._rate_limiter.acquire("duckduckgo")
        html = await self._fetch_page(
            "https://html.duckduckgo.com/html/",
            params={"q": query},
            engine="duckduckgo",
            headers=self._rate_limiter.get_headers(self._headers),
        )
        if not html:
            return []
        urls = self._extract_urls_from_html(html)
        log.info("duckduckgo  found=%d  query=%r", len(urls), query)
        return urls[:max_results]

    async def search_google(
        self, query: str, *, max_results: int = 10
    ) -> list[str]:
        """Search Google and return result URLs.

        Note: Google actively mitigates bot traffic.  This method may return
        empty results when Google serves a CAPTCHA or blocks the request.

        Parameters
        ----------
        query:
            The search query / dork string.
        max_results:
            Maximum number of URLs to return.

        Returns
        -------
        list[str]
            External HTTP/HTTPS URLs extracted from the result page.
        """
        if "google" in self._blocked_engines:
            return []
        log.info("google  query=%r", query)
        await self._rate_limiter.acquire("google")
        html = await self._fetch_page(
            "https://www.google.com/search",
            params={"q": query, "num": max_results},
            engine="google",
            headers=self._rate_limiter.get_headers(self._headers),
        )
        if not html:
            return []
        urls = self._extract_urls_from_html(html)
        log.info("google  found=%d  query=%r", len(urls), query)
        return urls[:max_results]

    async def search_yandex(
        self, query: str, *, max_results: int = 10
    ) -> list[str]:
        """Search Yandex and return result URLs.

        Parameters
        ----------
        query:
            The search query / dork string.
        max_results:
            Maximum number of URLs to return.

        Returns
        -------
        list[str]
            External HTTP/HTTPS URLs extracted from the result page.
        """
        if "yandex" in self._blocked_engines:
            return []
        log.info("yandex  query=%r", query)
        await self._rate_limiter.acquire("yandex")
        html = await self._fetch_page(
            "https://yandex.com/search/",
            params={"text": query, "numdoc": max_results},
            engine="yandex",
            headers=self._rate_limiter.get_headers(self._headers),
        )
        if not html:
            return []
        urls = self._extract_urls_from_html(html)
        log.info("yandex  found=%d  query=%r", len(urls), query)
        return urls[:max_results]

    async def search_bing(
        self, query: str, *, max_results: int = 10
    ) -> list[str]:
        """Search Bing and return result URLs.

        Uses the standard Bing web search endpoint.  Bing's ``count``
        parameter caps the number of results returned per page.

        Parameters
        ----------
        query:
            The search query / dork string.
        max_results:
            Maximum number of URLs to return.

        Returns
        -------
        list[str]
            External HTTP/HTTPS URLs extracted from the result page.
        """
        if "bing" in self._blocked_engines:
            return []
        log.info("bing  query=%r", query)
        await self._rate_limiter.acquire("bing")
        html = await self._fetch_page(
            "https://www.bing.com/search",
            params={"q": query, "count": max_results},
            engine="bing",
            headers=self._rate_limiter.get_headers(self._headers),
        )
        if not html:
            return []
        urls = self._extract_urls_from_html(html)
        log.info("bing  found=%d  query=%r", len(urls), query)
        return urls[:max_results]

    async def search_all(
        self,
        query: str,
        *,
        engines: tuple[str, ...] = ("duckduckgo", "google", "bing", "yandex"),
        max_results: int = 10,
    ) -> list[str]:
        """Search *query* across all *engines* and return deduplicated URLs.

        Parameters
        ----------
        query:
            The search query / dork string.
        engines:
            Names of search engines to query.  Each name must be one of
            ``"duckduckgo"``, ``"google"``, ``"bing"``, or ``"yandex"``.
        max_results:
            Maximum number of URLs to return *per engine*.

        Returns
        -------
        list[str]
            Deduplicated list of external URLs from all engines.
        """
        _engine_map = {
            "duckduckgo": self.search_duckduckgo,
            "google": self.search_google,
            "bing": self.search_bing,
            "yandex": self.search_yandex,
        }
        combined: list[str] = []
        for engine_name in engines:
            fn = _engine_map.get(engine_name)
            if fn is None:
                log.warning("search_all  unknown engine=%r  skipping", engine_name)
                continue
            urls = await fn(query, max_results=max_results)
            combined.extend(urls)

        return list(dict.fromkeys(combined))  # deduplicate, preserve order

    async def search_with_dorks(
        self,
        *,
        engines: tuple[str, ...] = ("duckduckgo", "google", "bing", "yandex"),
        max_dorks: Optional[int] = None,
        max_results_per_query: int = 10,
        dork_sources: str = "all",
    ) -> list[str]:
        """Run generated dork queries across *engines* and aggregate URLs.

        Dork queries are selected by *dork_sources*:

        * ``"github"`` — dorks restricted to ``site:github.com`` (produced by
          :class:`~ai_finder.discovery.GoogleDorkGenerator`).  These find AI
          config files specifically on GitHub.
        * ``"web"`` — generic open-web dorks with **no** host restriction
          (produced by :class:`~ai_finder.discovery.WebDorkGenerator`).
          These find AI config files on *any* publicly indexed website,
          including personal servers, CDNs, S3 sites, and documentation
          portals.
        * ``"all"`` *(default)* — both sets combined, providing the widest
          possible coverage.

        The resulting URLs are deduplicated before being returned so that
        the caller can pass them directly to
        :meth:`~ai_finder.crawler.Crawler.filter_reachable`.

        Parameters
        ----------
        engines:
            Search engines to use.  Valid values: ``"duckduckgo"``,
            ``"google"``, ``"bing"``, ``"yandex"``.
        max_dorks:
            Maximum number of dork queries to submit in total.  ``None``
            means no limit.
        max_results_per_query:
            Maximum URLs collected from each individual query/engine pair.
        dork_sources:
            Which dork generator(s) to use: ``"github"``, ``"web"``, or
            ``"all"`` (default).

        Returns
        -------
        list[str]
            Deduplicated list of candidate URLs harvested from search results.
        """
        dorks = _build_dorks(dork_sources)
        if max_dorks is not None:
            dorks = dorks[:max_dorks]

        log.info(
            "search_with_dorks  dorks=%d  engines=%s  sources=%s",
            len(dorks),
            engines,
            dork_sources,
        )
        all_urls: list[str] = []
        for dork in dorks:
            urls = await self.search_all(
                dork.query,
                engines=engines,
                max_results=max_results_per_query,
            )
            log.info(
                "search_with_dorks  dork=%r  found=%d", dork.query, len(urls)
            )
            all_urls.extend(urls)

        result = list(dict.fromkeys(all_urls))
        if self._blocked_engines:
            log.warning(
                "search_with_dorks  blocked_engines=%s  "
                "(CAPTCHA or persistent rate-limit — consider removing them "
                "or adding proxy support)",
                sorted(self._blocked_engines),
            )
        log.info("search_with_dorks  total_unique=%d", len(result))
        return result

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    # URL path fragments that indicate a CAPTCHA / bot-block page.  Checked
    # against the *final* URL after redirects (resp.url).
    _CAPTCHA_PATH_FRAGMENTS: tuple[str, ...] = (
        "/showcaptcha",   # Yandex
        "/sorry/index",   # Google reCAPTCHA
        "/search/unlock", # Bing bot-unlock
    )

    async def _handle_captcha(self, captcha_url: str, engine_url: str) -> None:
        """Open *captcha_url* in the default browser and wait asynchronously
        for the user to solve it before continuing.

        The method prints a prominent banner, opens the browser, then
        suspends the coroutine (without blocking the event loop) until the
        user presses **Enter**.  After returning, ``_fetch_page`` retries
        the original request — Yandex and Google often use IP-based
        challenges, so a solved CAPTCHA in the browser is enough to lift
        the block for a short window.
        """
        print(
            f"\n{'=' * 62}\n"
            f"[!] CAPTCHA / bot-block detected\n"
            f"    Engine  : {engine_url}\n"
            f"    CAPTCHA : {captcha_url}\n"
            f"\n"
            f"    A browser window will open. Solve the CAPTCHA there,\n"
            f"    then come back here and press Enter to continue...\n"
            f"{'=' * 62}",
            flush=True,
        )
        webbrowser.open(captcha_url)
        # Run blocking stdin.readline in a thread so the event loop stays free.
        loop = asyncio.get_event_loop()
        await loop.run_in_executor(None, sys.stdin.readline)
        print("[*] Resuming URL extraction...", flush=True)

    async def _fetch_page(
        self,
        url: str,
        params: dict,
        *,
        engine: str = "default",
        headers: Optional[dict[str, str]] = None,
        _retry: bool = False,
    ) -> str:
        """Fetch *url* with *params* and return the response text.

        When a CAPTCHA / bot-block redirect is detected and
        ``captcha_pause`` is enabled, the method opens the CAPTCHA URL in
        the default browser, waits asynchronously for the user to press
        Enter, then retries the request **once**.  If the second attempt
        also hits a CAPTCHA the engine is skipped and an empty string is
        returned.

        HTTP 429 responses trigger a fixed backoff pause (looked up from the
        :class:`~ai_finder.rate_limiter.RateLimiter` using *engine*) and
        are retried once.

        Returns an empty string on any error or non-200 response.
        """
        try:
            assert self._session is not None, "Call inside async context manager"
            async with self._session.get(
                url, params=params, headers=headers
            ) as resp:
                final_url = str(resp.url)
                # Detect CAPTCHA / bot-block redirects before reading the body.
                for fragment in self._CAPTCHA_PATH_FRAGMENTS:
                    if fragment in final_url:
                        if self._captcha_pause and not _retry:
                            await self._handle_captcha(final_url, url)
                            # Retry once after the user solved the CAPTCHA.
                            return await self._fetch_page(
                                url, params,
                                engine=engine, headers=headers, _retry=True,
                            )
                        # Trip the circuit breaker — skip this engine for the
                        # rest of the session to avoid flooding logs.
                        self._blocked_engines.add(engine)
                        log.warning(
                            "_fetch_page  CAPTCHA/bot-block detected  "
                            "engine=%s  final_url=%s  "
                            "— engine disabled for this session",
                            engine,
                            final_url,
                        )
                        return ""
                if resp.status == 403:
                    # Many engines return 403 when they detect bot traffic.
                    self._blocked_engines.add(engine)
                    log.warning(
                        "_fetch_page  403 bot-block  engine=%s  url=%s  "
                        "— engine disabled for this session",
                        engine, url,
                    )
                    return ""
                if resp.status == 429:
                    if not _retry:
                        pause = self._rate_limiter.get_backoff_pause(engine)
                        log.warning(
                            "_fetch_page  429 rate-limited  engine=%s  "
                            "backoff=%.0fs  url=%s",
                            engine, pause, url,
                        )
                        await asyncio.sleep(pause)
                        return await self._fetch_page(
                            url, params,
                            engine=engine, headers=headers, _retry=True,
                        )
                    # Retry exhausted — trip circuit breaker.
                    self._blocked_engines.add(engine)
                    log.warning(
                        "_fetch_page  429 retry exhausted  engine=%s  url=%s  "
                        "— engine disabled for this session",
                        engine, url,
                    )
                    return ""
                if resp.status != 200:
                    log.warning(
                        "_fetch_page  non-200  status=%d  url=%s", resp.status, url
                    )
                    return ""
                return await resp.text(errors="replace")
        except Exception as exc:  # noqa: BLE001
            log.warning("_fetch_page  error  url=%s  error=%s", url, exc)
            return ""

    @staticmethod
    def _extract_urls_from_html(
        html: str,
        *,
        exclude_domains: frozenset[str] = _EXCLUDED_DOMAINS,
    ) -> list[str]:
        """Extract external result URLs from a search-engine HTML page.

        Handles:
        * Plain ``href`` values that start with ``http://`` or ``https://``.
        * Google's redirect URLs of the form ``/url?q=https://...``.
        * DuckDuckGo's ``uddg=`` redirect parameter.

        Parameters
        ----------
        html:
            Raw HTML text of the search result page.
        exclude_domains:
            Set of bare domain names (no ``www.`` prefix) that should be
            excluded from the results.

        Returns
        -------
        list[str]
            Deduplicated list of external URLs in page order.
        """
        soup = BeautifulSoup(html, "lxml")
        urls: list[str] = []
        seen: set[str] = set()

        for tag in soup.find_all("a", href=True):
            href: str = tag["href"]

            # --- unwrap Google redirect URLs ---
            if href.startswith("/url?"):
                qs = parse_qs(href[5:])
                if "q" in qs:
                    href = qs["q"][0]

            # --- unwrap DuckDuckGo redirect parameter ---
            # Parse the URL first to safely check the netloc before inspecting
            # the query string, preventing substring-matching on the full href.
            if href.startswith(("http://", "https://")):
                parsed_early = urlparse(href)
                early_netloc = parsed_early.netloc.lower()
                if early_netloc in ("duckduckgo.com", "www.duckduckgo.com"):
                    qs = parse_qs(parsed_early.query)
                    if "uddg" in qs:
                        href = qs["uddg"][0]

            # Only keep external http(s) URLs
            if not href.startswith(("http://", "https://")):
                continue

            parsed = urlparse(href)
            netloc = parsed.netloc.lower()
            # Strip leading 'www.' for domain matching
            base_domain = netloc[4:] if netloc.startswith("www.") else netloc

            if base_domain in exclude_domains or netloc in exclude_domains:
                continue

            if href in seen:
                continue

            seen.add(href)
            urls.append(href)

        return urls
