"""
web_search.py — Web search engine dorking module.

Searches Google, DuckDuckGo, and Yandex using dork queries generated by
:mod:`ai_finder.discovery` to discover URLs of AI agent configuration files.
The returned URLs are candidates that can then be verified and downloaded by
the rest of the pipeline.

Typical usage
-------------
    import asyncio
    from ai_finder.web_search import WebSearcher

    async def main():
        async with WebSearcher() as searcher:
            urls = await searcher.search_with_dorks(
                engines=("duckduckgo",),
                max_dorks=5,
            )
            print(f"Found {len(urls)} candidate URL(s)")

    asyncio.run(main())
"""

from __future__ import annotations

import re
from typing import Optional
from urllib.parse import parse_qs, urlparse

import aiohttp
from bs4 import BeautifulSoup

from ai_finder.discovery import GoogleDorkGenerator
from ai_finder.extractor import DEFAULT_TIMEOUT
from ai_finder.logger import get_logger

log = get_logger(__name__)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

#: Domains that should never appear in search results (search-engine own
#: pages, ad-redirect hosts, etc.).
_EXCLUDED_DOMAINS: frozenset[str] = frozenset(
    {
        "google.com",
        "google.co.uk",
        "google.co.in",
        "accounts.google.com",
        "support.google.com",
        "maps.google.com",
        "duckduckgo.com",
        "yandex.com",
        "yandex.ru",
        "youtube.com",
        "wikipedia.org",
        "w3.org",
    }
)

#: Browser-like User-Agent used for search-engine requests.
_SEARCH_USER_AGENT = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
    "AppleWebKit/537.36 (KHTML, like Gecko) "
    "Chrome/120.0.0.0 Safari/537.36"
)

#: Default HTTP headers sent with every search-engine request.
_SEARCH_HEADERS: dict[str, str] = {
    "User-Agent": _SEARCH_USER_AGENT,
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
    "Accept-Language": "en-US,en;q=0.5",
}


# ---------------------------------------------------------------------------
# WebSearcher
# ---------------------------------------------------------------------------


class WebSearcher:
    """Search Google, DuckDuckGo, and Yandex using dork queries.

    Results are parsed from the HTML search-result pages and returned as a
    list of external URLs.  The caller is responsible for verifying
    reachability and downloading content.

    Parameters
    ----------
    session:
        Optional pre-existing :class:`aiohttp.ClientSession`.  When omitted
        the searcher manages its own session lifecycle.
    timeout:
        ``aiohttp.ClientTimeout`` applied to every HTTP request.
    headers:
        HTTP headers sent with every search-engine request.  Defaults to
        browser-like headers to reduce bot-detection friction.
    """

    def __init__(
        self,
        session: Optional[aiohttp.ClientSession] = None,
        timeout: aiohttp.ClientTimeout = DEFAULT_TIMEOUT,
        headers: Optional[dict[str, str]] = None,
    ) -> None:
        self._session = session
        self._owns_session = session is None
        self._timeout = timeout
        self._headers = headers if headers is not None else _SEARCH_HEADERS

    # ------------------------------------------------------------------
    # Session lifecycle
    # ------------------------------------------------------------------

    async def __aenter__(self) -> "WebSearcher":
        if self._owns_session:
            self._session = aiohttp.ClientSession(
                timeout=self._timeout, headers=self._headers
            )
        return self

    async def __aexit__(self, *_: object) -> None:
        if self._owns_session and self._session:
            await self._session.close()

    # ------------------------------------------------------------------
    # Public search API
    # ------------------------------------------------------------------

    async def search_duckduckgo(
        self, query: str, *, max_results: int = 10
    ) -> list[str]:
        """Search DuckDuckGo (HTML endpoint) and return result URLs.

        Uses the ``html.duckduckgo.com`` endpoint which does not require
        JavaScript and is friendlier to programmatic access than the
        JavaScript-rendered default interface.

        Parameters
        ----------
        query:
            The search query / dork string.
        max_results:
            Maximum number of URLs to return.

        Returns
        -------
        list[str]
            External HTTP/HTTPS URLs extracted from the result page.
        """
        log.debug("duckduckgo  query=%r", query)
        html = await self._fetch_page(
            "https://html.duckduckgo.com/html/",
            params={"q": query},
        )
        if not html:
            return []
        urls = self._extract_urls_from_html(html)
        log.debug("duckduckgo  found=%d  query=%r", len(urls), query)
        return urls[:max_results]

    async def search_google(
        self, query: str, *, max_results: int = 10
    ) -> list[str]:
        """Search Google and return result URLs.

        Note: Google actively mitigates bot traffic.  This method may return
        empty results when Google serves a CAPTCHA or blocks the request.

        Parameters
        ----------
        query:
            The search query / dork string.
        max_results:
            Maximum number of URLs to return.

        Returns
        -------
        list[str]
            External HTTP/HTTPS URLs extracted from the result page.
        """
        log.debug("google  query=%r", query)
        html = await self._fetch_page(
            "https://www.google.com/search",
            params={"q": query, "num": max_results},
        )
        if not html:
            return []
        urls = self._extract_urls_from_html(html)
        log.debug("google  found=%d  query=%r", len(urls), query)
        return urls[:max_results]

    async def search_yandex(
        self, query: str, *, max_results: int = 10
    ) -> list[str]:
        """Search Yandex and return result URLs.

        Parameters
        ----------
        query:
            The search query / dork string.
        max_results:
            Maximum number of URLs to return.

        Returns
        -------
        list[str]
            External HTTP/HTTPS URLs extracted from the result page.
        """
        log.debug("yandex  query=%r", query)
        html = await self._fetch_page(
            "https://yandex.com/search/",
            params={"text": query, "numdoc": max_results},
        )
        if not html:
            return []
        urls = self._extract_urls_from_html(html)
        log.debug("yandex  found=%d  query=%r", len(urls), query)
        return urls[:max_results]

    async def search_all(
        self,
        query: str,
        *,
        engines: tuple[str, ...] = ("duckduckgo", "google", "yandex"),
        max_results: int = 10,
    ) -> list[str]:
        """Search *query* across all *engines* and return deduplicated URLs.

        Parameters
        ----------
        query:
            The search query / dork string.
        engines:
            Names of search engines to query.  Each name must be one of
            ``"duckduckgo"``, ``"google"``, or ``"yandex"``.
        max_results:
            Maximum number of URLs to return *per engine*.

        Returns
        -------
        list[str]
            Deduplicated list of external URLs from all engines.
        """
        _engine_map = {
            "duckduckgo": self.search_duckduckgo,
            "google": self.search_google,
            "yandex": self.search_yandex,
        }
        combined: list[str] = []
        for engine_name in engines:
            fn = _engine_map.get(engine_name)
            if fn is None:
                log.warning("search_all  unknown engine=%r  skipping", engine_name)
                continue
            urls = await fn(query, max_results=max_results)
            combined.extend(urls)

        return list(dict.fromkeys(combined))  # deduplicate, preserve order

    async def search_with_dorks(
        self,
        *,
        engines: tuple[str, ...] = ("duckduckgo", "google", "yandex"),
        max_dorks: Optional[int] = None,
        max_results_per_query: int = 10,
    ) -> list[str]:
        """Run all generated dork queries across *engines* and aggregate URLs.

        Dork queries are produced by
        :class:`~ai_finder.discovery.GoogleDorkGenerator`.  The resulting
        URLs are deduplicated before being returned so that the caller can
        pass them directly to :meth:`~ai_finder.crawler.Crawler.filter_reachable`.

        Parameters
        ----------
        engines:
            Search engines to use.
        max_dorks:
            Maximum number of dork queries to submit per engine.  ``None``
            means no limit.
        max_results_per_query:
            Maximum URLs collected from each individual query/engine pair.

        Returns
        -------
        list[str]
            Deduplicated list of candidate URLs harvested from search results.
        """
        gen = GoogleDorkGenerator()
        dorks = gen.all_dorks()
        if max_dorks is not None:
            dorks = dorks[:max_dorks]

        log.info(
            "search_with_dorks  dorks=%d  engines=%s", len(dorks), engines
        )
        all_urls: list[str] = []
        for dork in dorks:
            urls = await self.search_all(
                dork.query,
                engines=engines,
                max_results=max_results_per_query,
            )
            log.debug(
                "search_with_dorks  dork=%r  found=%d", dork.query, len(urls)
            )
            all_urls.extend(urls)

        result = list(dict.fromkeys(all_urls))
        log.info("search_with_dorks  total_unique=%d", len(result))
        return result

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    async def _fetch_page(self, url: str, params: dict) -> str:
        """Fetch *url* with *params* and return the response text.

        Returns an empty string on any error or non-200 response so that
        callers can treat all failure modes uniformly.
        """
        try:
            assert self._session is not None, "Call inside async context manager"
            async with self._session.get(url, params=params) as resp:
                if resp.status != 200:
                    log.warning(
                        "_fetch_page  non-200  status=%d  url=%s", resp.status, url
                    )
                    return ""
                return await resp.text(errors="replace")
        except Exception as exc:  # noqa: BLE001
            log.warning("_fetch_page  error  url=%s  error=%s", url, exc)
            return ""

    @staticmethod
    def _extract_urls_from_html(
        html: str,
        *,
        exclude_domains: frozenset[str] = _EXCLUDED_DOMAINS,
    ) -> list[str]:
        """Extract external result URLs from a search-engine HTML page.

        Handles:
        * Plain ``href`` values that start with ``http://`` or ``https://``.
        * Google's redirect URLs of the form ``/url?q=https://...``.
        * DuckDuckGo's ``uddg=`` redirect parameter.

        Parameters
        ----------
        html:
            Raw HTML text of the search result page.
        exclude_domains:
            Set of bare domain names (no ``www.`` prefix) that should be
            excluded from the results.

        Returns
        -------
        list[str]
            Deduplicated list of external URLs in page order.
        """
        soup = BeautifulSoup(html, "lxml")
        urls: list[str] = []
        seen: set[str] = set()

        for tag in soup.find_all("a", href=True):
            href: str = tag["href"]

            # --- unwrap Google redirect URLs ---
            if href.startswith("/url?"):
                qs = parse_qs(href[5:])
                if "q" in qs:
                    href = qs["q"][0]

            # --- unwrap DuckDuckGo redirect parameter ---
            if "duckduckgo.com" in href and "uddg=" in href:
                parsed_ddg = urlparse(href)
                qs = parse_qs(parsed_ddg.query)
                if "uddg" in qs:
                    href = qs["uddg"][0]

            # Only keep external http(s) URLs
            if not href.startswith(("http://", "https://")):
                continue

            parsed = urlparse(href)
            netloc = parsed.netloc.lower()
            # Strip leading 'www.' for domain matching
            base_domain = netloc[4:] if netloc.startswith("www.") else netloc

            if base_domain in exclude_domains or netloc in exclude_domains:
                continue

            if href in seen:
                continue

            seen.add(href)
            urls.append(href)

        return urls
